version: '3'
services:
  mysql:
    image: mysql:5
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: osclass
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
